import {Router} from 'express';

const SCREENS = [
  {order: 0, name: 'Design System', api: []},
  {order: 1, name: 'Splash', api: ['GET /api/v1/health']},
  {order: 2, name: 'Language Selection', api: ['GET /api/v1/master/languages', 'PUT /api/v1/profile/settings']},
  {order: 3, name: 'Login', api: ['POST /api/v1/auth/otp/send']},
  {order: 4, name: 'OTP Verification', api: ['POST /api/v1/auth/otp/verify']},
  {order: 5, name: 'Continue with Google', api: ['POST /api/v1/auth/social']},
  {order: 6, name: 'Continue with Facebook', api: ['POST /api/v1/auth/social']},
  {order: 7, name: 'Continue with Email', api: ['POST /api/v1/auth/otp/send']},
  {order: 8, name: 'Signup Personal Details', api: ['POST /api/v1/auth/register']},
  {order: 9, name: 'Signup Spiritual Details', api: ['POST /api/v1/auth/complete-profile']},
  {order: 10, name: 'Profile Photo', api: ['POST /api/v1/auth/complete-profile']},
  {order: 11, name: 'Registration Confirmation', api: ['GET /api/v1/auth/profile']},
  {order: 12, name: 'Home Dashboard', api: ['GET /api/v1/japa/summary']},
  {order: 13, name: 'Notifications', api: ['GET /api/v1/notifications']},
  {order: 14, name: 'Profile', api: ['GET /api/v1/auth/profile']},
  {order: 15, name: 'Settings', api: ['GET /api/v1/profile/settings']},
  {order: 16, name: 'Language Settings', api: ['GET /api/v1/master/languages']},
  {order: 17, name: 'Japa Category Selection', api: ['GET /api/v1/japa/summary']},
  {order: 18, name: 'Community Japa', api: ['GET /api/v1/japa/community']},
  {order: 19, name: 'Mantra Selection', api: ['GET /api/v1/mantras']},
  {order: 20, name: 'Goal Selection', api: ['POST /api/v1/japa-goals']},
  {order: 21, name: 'Reference Chant Recording', api: ['POST /api/v1/japa/reference']},
  {order: 22, name: 'Smart Japa Counting', api: ['POST /api/v1/japa/session']},
  {order: 23, name: 'Japa Pause AutoLock', api: ['GET /api/v1/profile/settings']},
  {order: 24, name: 'Japa Progress', api: ['GET /api/v1/japa/progress']},
  {order: 25, name: 'My Japa Private', api: ['GET /api/v1/personal-mantras']},
  {order: 26, name: 'Challenge Japa', api: ['GET /api/v1/challenges']},
  {order: 27, name: 'Challenge Details', api: ['GET /api/v1/challenges/:id']},
  {order: 28, name: 'Challenge Progress', api: ['GET /api/v1/challenges/:id/progress']},
  {order: 29, name: 'Challenge Leaderboard', api: ['GET /api/v1/challenges/:id/leaderboard']},
  {order: 30, name: 'Challenge Completion Rating', api: ['POST /api/v1/challenges/:id/rate']},
  {order: 31, name: 'User Japa Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 32, name: 'Daily Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 33, name: 'Weekly Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 34, name: 'Monthly Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 35, name: 'Lifetime Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 36, name: 'Goal Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 37, name: 'Streak Analytics', api: ['GET /api/v1/japa/analytics']},
  {order: 38, name: 'Baanalingam', api: ['POST /api/v1/bana-lingam']},
  {order: 39, name: 'Baanalingam Payment', api: ['POST /api/v1/donations/checkout']},
  {order: 40, name: 'Baanalingam Review', api: ['POST /api/v1/donations/checkout']},
  {order: 41, name: 'Payment Confirmation', api: ['POST /api/v1/donations/checkout']},
  {order: 42, name: 'Annadanam', api: ['GET /api/v1/donations/catalog']},
  {order: 43, name: 'Japa Annadanam', api: ['GET /api/v1/japa/milestones']},
  {order: 44, name: 'General Annadanam', api: ['POST /api/v1/donations/checkout']},
  {order: 45, name: 'Donation Form', api: ['POST /api/v1/donations/checkout']},
  {order: 46, name: 'UPI QR Payment Donation', api: ['POST /api/v1/donations/checkout']},
  {order: 47, name: 'Donation Confirmation', api: ['POST /api/v1/donations/checkout']},
  {order: 48, name: 'Nithya Homam', api: ['GET /api/v1/donations/catalog']},
  {order: 49, name: 'Homam Enrollment', api: ['POST /api/v1/donations/checkout']},
  {order: 50, name: 'UPI QR Payment Homam', api: ['POST /api/v1/donations/checkout']},
  {order: 51, name: 'Homam Enrollment Confirmation', api: ['POST /api/v1/donations/checkout']},
  {order: 52, name: 'Orders List', api: ['GET /api/v1/orders']},
  {order: 53, name: 'Order Details', api: ['GET /api/v1/orders/:id/tracking']},
  {order: 54, name: 'Order Tracking', api: ['GET /api/v1/orders/:id/tracking']},
  {order: 55, name: 'Delivery Status', api: ['GET /api/v1/orders/:id/tracking']},
  {order: 56, name: 'Customer Care', api: ['GET /api/v1/customer-care/config']},
  {order: 57, name: 'Raise Ticket', api: ['POST /api/v1/customer-care']},
  {order: 58, name: 'WhatsApp Support', api: ['GET /api/v1/customer-care/config']},
  {order: 59, name: 'Call Support', api: ['GET /api/v1/customer-care/config']},
  {order: 60, name: 'FAQ', api: ['GET /api/v1/customer-care/faq']},
  {order: 61, name: 'Feedback Form', api: ['POST /api/v1/feedback']},
  {order: 62, name: 'Star Rating', api: ['POST /api/v1/feedback']},
  {order: 63, name: 'Feedback Confirmation', api: ['POST /api/v1/feedback']},
  {order: 64, name: 'All Screens Index', api: ['GET /api/v1/screens']},
];

const router = Router();

router.get('/', (_req, res) => {
  res.status(200).json({
    success: true,
    message: 'User screens 0-64',
    data: SCREENS,
  });
});

export default router;
