export type ScreenEntry = {
  order: number;
  name: string;
  route: string;
  params?: Record<string, unknown>;
};

export const SCREEN_CATALOG: ScreenEntry[] = [
  {order: 0, name: 'Design System', route: 'DesignSystem'},
  {order: 1, name: 'Splash', route: 'Splash'},
  {order: 2, name: 'Language Selection', route: 'LanguageSelect'},
  {order: 3, name: 'Login', route: 'Login'},
  {
    order: 4,
    name: 'OTP Verification',
    route: 'OtpScreen',
    params: {
      phoneNumber: '+919999999999',
      mobileCountryCode: '+91',
      mobileNumber: '9999999999',
      email: 'devotee@japasiddhi.com',
      sentTo: 'devotee@japasiddhi.com',
    },
  },
  {order: 5, name: 'Continue with Google', route: 'SocialAuth', params: {provider: 'Google'}},
  {order: 6, name: 'Continue with Facebook', route: 'SocialAuth', params: {provider: 'Facebook'}},
  {order: 7, name: 'Continue with Email', route: 'SocialAuth', params: {provider: 'Email'}},
  {order: 8, name: 'Signup Personal Details', route: 'SignupPersonal'},
  {order: 9, name: 'Signup Spiritual Details', route: 'SignupSpiritual'},
  {order: 10, name: 'Profile Photo', route: 'SignupPhoto'},
  {order: 11, name: 'Registration Confirmation', route: 'RegistrationComplete'},
  {order: 12, name: 'Home Dashboard', route: 'Home'},
  {order: 13, name: 'Notifications', route: 'Notifications'},
  {order: 14, name: 'Profile', route: 'Profile'},
  {order: 15, name: 'Settings', route: 'Settings'},
  {order: 16, name: 'Language Settings', route: 'LanguageSelect', params: {fromSettings: true}},
  {order: 17, name: 'Japa Category Selection', route: 'JapaHub'},
  {order: 18, name: 'Community Japa', route: 'CommunityJapa'},
  {order: 19, name: 'Mantra Selection', route: 'MantraSelect', params: {mode: 'community'}},
  {order: 20, name: 'Goal Selection', route: 'GoalSelect', params: {mode: 'community', goal: 10800}},
  {order: 21, name: 'Reference Chant Recording', route: 'ReferenceChant', params: {mode: 'community', goal: 10800}},
  {order: 22, name: 'Smart Japa Counting', route: 'Chant', params: {mode: 'community', goal: 10800}},
  {order: 23, name: 'Japa Pause AutoLock', route: 'JapaPaused', params: {count: 108, goal: 10800}},
  {order: 24, name: 'Japa Progress', route: 'JapaProgress', params: {count: 108, goal: 10800}},
  {
    order: 24.5,
    name: 'Japa Goal Complete',
    route: 'JapaGoalComplete',
    params: {count: 108, goal: 108, mode: 'community', mantraId: 1},
  },
  {order: 25, name: 'My Japa Private', route: 'PrivateJapa'},
  {order: 26, name: 'Challenge Japa', route: 'Challenges'},
  {order: 27, name: 'Challenge Details', route: 'ChallengeDetails', params: {id: 1}},
  {order: 27.1, name: 'Challenge Rules', route: 'ChallengeRules'},
  {order: 27.2, name: 'Reward Terms', route: 'RewardTerms'},
  {order: 28, name: 'Challenge Progress Tracking', route: 'ChallengeProgress', params: {id: 1}},
  {order: 29, name: 'Challenge Leaderboard', route: 'ChallengeLeaderboard', params: {id: 1}},
  {
    order: 29.5,
    name: 'My Challenge Rank',
    route: 'ChallengeMyRank',
    params: {id: 1, rank: 4, currentValue: 4200, totalPlayers: 80},
  },
  {
    order: 29.6,
    name: 'Choose Your Reward',
    route: 'ChallengeRewardSelect',
    params: {id: 1},
  },
  {
    order: 29.7,
    name: 'Reward Selected Confirmation',
    route: 'ChallengeRewardConfirm',
    params: {id: 1, rewardId: 1, rewardName: 'Rudraksha'},
  },
  {
    order: 29.71,
    name: 'Reward Claimed',
    route: 'ChallengeRewardClaimed',
    params: {id: 1, rewardName: 'Spatik mala'},
  },
  {
    order: 29.72,
    name: 'Reward Delivery',
    route: 'ChallengeRewardDelivery',
    params: {id: 1, rewardName: 'Spatik mala'},
  },
  {
    order: 29.73,
    name: 'Reward Order Created',
    route: 'ChallengeRewardOrderCreated',
    params: {
      id: 1,
      rewardName: 'Spatik mala',
      orderId: 1,
      orderNumber: 'RW10281',
    },
  },
  {order: 30, name: 'Challenge Completion Rating', route: 'ChallengeComplete', params: {id: 1}},
  {order: 31, name: 'User Japa Analytics', route: 'JapaOverview'},
  {order: 32, name: 'Daily Analytics', route: 'DailyAnalytics'},
  {order: 33, name: 'Weekly Analytics', route: 'WeeklyAnalytics'},
  {order: 34, name: 'Monthly Analytics', route: 'MonthlyAnalytics'},
  {order: 35, name: 'Lifetime Analytics', route: 'LifetimeAnalytics'},
  {order: 36, name: 'Goal Analytics', route: 'GoalAnalytics'},
  {order: 37, name: 'Streak Analytics', route: 'StreakAnalytics'},
  {order: 38, name: 'Baanalingam', route: 'BanaLingam'},
  {
    order: 39,
    name: 'Baanalingam Payment',
    route: 'BanaLingamPayment',
    params: {
      kind: 'BANA_LINGAM',
      title: 'Proceed to Pay',
      heading: 'Scan the UPI QR',
      itemName: 'Baanalingam',
      subtitle: 'Scan this QR to complete your offering.',
      amount: 1008,
      showSummary: true,
      methodLabel: 'METHOD',
      button: 'I HAVE PAID',
    },
  },
  {order: 40, name: 'Baanalingam Review', route: 'BanaLingamReview'},
  {
    order: 41,
    name: 'Payment Confirmation',
    route: 'PaymentConfirmation',
    params: {itemName: 'Baanalingam', orderNumber: 'JS10028'},
  },
  {order: 42, name: 'Annadanam', route: 'Donate'},
  {order: 43, name: 'Japa Annadanam', route: 'JapaAnnadanam'},
  {order: 43, name: 'Japa Annadanam Notification', route: 'MilestoneNotifications'},
  {order: 44, name: 'General Annadanam', route: 'GeneralAnnadanam'},
  {
    order: 45,
    name: 'Donation Form',
    route: 'DonationForm',
    params: {kind: 'GENERAL', amount: 1008, itemName: 'General Annadanam'},
  },
  {
    order: 46,
    name: 'UPI QR Payment Donation',
    route: 'DonationPayment',
    params: {
      kind: 'ANNADANAM',
      title: 'Proceed to Pay',
      heading: 'Scan the UPI QR',
      itemName: 'Annadanam Donation',
      subtitle: 'Scan this QR with any UPI app.',
      amount: 1008,
      button: 'I HAVE PAID',
    },
  },
  {
    order: 47,
    name: 'Donation Confirmation',
    route: 'DonationConfirmation',
    params: {itemName: 'Annadanam', confirmationId: 'ANN10281'},
  },
  {order: 48, name: 'Nithya Homam', route: 'NithyaHomam'},
  {order: 49, name: 'Homam Enrollment', route: 'HomamEnroll'},
  {
    order: 50,
    name: 'UPI QR Payment Homam',
    route: 'HomamPayment',
    params: {
      kind: 'NITHYA_HOMAM',
      title: 'Proceed to Pay',
      heading: 'Scan the UPI QR',
      itemName: 'Nithya Homam Enrollment',
      subtitle: 'Scan this QR to complete enrollment.',
      amount: 1008,
      showSummary: true,
      methodLabel: 'METHOD',
      button: 'I HAVE PAID',
    },
  },
  {
    order: 51,
    name: 'Homam Enrollment Confirmation',
    route: 'HomamConfirmation',
    params: {confirmationId: 'NH10281'},
  },
  {order: 52, name: 'Orders List', route: 'Orders'},
  {order: 53, name: 'Order Details', route: 'OrderDetails', params: {id: 1}},
  {order: 54, name: 'Order Tracking', route: 'OrderTracking', params: {id: 1}},
  {order: 55, name: 'Delivery Status', route: 'DeliveryStatus', params: {id: 1}},
  {order: 56, name: 'Customer Care', route: 'CustomerCare'},
  {order: 57, name: 'Raise Ticket', route: 'RaiseTicket'},
  {order: 58, name: 'WhatsApp Support', route: 'WhatsAppSupport'},
  {order: 59, name: 'Call Support', route: 'CallSupport'},
  {order: 60, name: 'FAQ', route: 'Faq'},
  {order: 61, name: 'Feedback Form', route: 'Feedback'},
  {order: 62, name: 'Star Rating', route: 'StarRating'},
  {order: 63, name: 'Feedback Confirmation', route: 'FeedbackConfirmation'},
  {order: 64, name: 'All Screens Index', route: 'ScreenIndex'},
];
